### ISSUE TITLE
[NOWEB] - Problem with knox (KnexTimeoutError)

### ISSUE THREAD

**Issue by borin98** [allburov/whatsapp-http-api#952]
### Describe the bug

Hello ! When i tried to scan a QR code to create a session using NOWEB engine, I got a error to login to insert the messages on the Postgress database with knox. When i tried to scan or create another session, the login happens normally, just with a number that have a lot of messages this happens

### Version

Get the WAHA version by calling `GET /api/version`

```json
{
"version": "2025.4.2",
"engine": "NOWEB",
"tier": "PLUS",
"browser": null
}
```

## Steps

**To Reproduce** Steps to reproduce the behavior:

1. Create a session via dashboard
2. Log-in with QR using a number that have more than 3000 messages
3. See error on docker logs

### Expected behavior

The expected behavior is to login without problems

### Docker Logs

```shell
wpp_waha_api  | Error upserting data: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?, sql: INSERT INTO "messages" ("jid", "id", "messageTimestamp", "data")
wpp_waha_api  |                  VALUES (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?), (?, ?, ?, ?)
wpp_waha_api  |                  ON CONFLICT(id) DO UPDATE
```

### Additional context
He's the docker compose file used for the project 

```yaml
services:
  waha-service:
    image: devlikeapro/waha-plus:noweb
    container_name: wpp_waha_api
    restart: always
    depends_on:
      - postgres-waha-db
    ports:
      - "3000:3000"
    env_file:
      - ./envs/waha/.env

  # PostgreSQL é usado para armazenar as sessões do WhatsApp
  # https://waha.devlike.pro/docs/how-to/storages/#media---postgresql
  postgres-waha-db:
    image: postgres:17
    container_name: waha_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./envs/postgress/.env
    command:
      - postgres
      - "-c"
      - "max_connections=3000"
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    env_file:
        - ./envs/n8n/.env
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pg_data: { }
  n8n_data: { }
```

## Additional notes

Using the ChatGPT Waha version, i got this history, maybe this also helps
https://chatgpt.com/share/681df51e-dae0-8010-bd76-d187239e9f1b

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
